export const GET_LAUNCHES_BEGIN='GET_LAUNCHES_BEGIN';
export const GET_LAUNCHES_SUCCESS='GET_LAUNCHES_SUCCESS';
export const GET_LAUNCHES_FAIL='GET_LAUNCHES_FAIL';

export const APPLY_FILTER_BEGIN='APPLY_FILTER_BEGIN';
export const APPLY_FILTER_SUCCESS='APPLY_FILTER_SUCCESS';
export const APPLY_FILTER_FAIL='APPLY_FILTER_FAIL';
