export const GET_PROGRAMS_BEGIN='GET_PROGRAMS_BEGIN';
export const GET_PROGRAMS_SUCCESS='GET_PROGRAMS_SUCCESS';
export const GET_PROGRAMS_FAIL='GET_PROGRAMS_FAIL';

export const APPLY_FILTER_BEGIN='APPLY_FILTER_BEGIN';
export const APPLY_FILTER_SUCCESS='APPLY_FILTER_SUCCESS';
export const APPLY_FILTER_FAIL='APPLY_FILTER_FAIL';
